services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_HOST: store

  store:
    image: "postgres:latest"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
