services:
 api:
  build: ./api
  ports:
  - "3000:3000"
  volumes:
  environment:
    POSTGRES_USER:
    POSTGRES_PASSWORD:
    POSTGRES_DB:
    POSTGRES_HOST: store

  store:
    build:
    ports: 
     - "3306:3306"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
